# Generated by Django 6.0.3 on 2026-03-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='progress_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='progress_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='progress_stage',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
