# Generated by Django 6.0.3 on 2026-03-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0002_processingjob_progress_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login success'), ('login_failed', 'Login failed'), ('upload_init', 'Upload initiated'), ('upload_complete', 'Upload completed'), ('process_queued', 'Asset queued'), ('process_completed', 'Asset ready'), ('process_failed', 'Asset failed'), ('clip_queued', 'Clip queued'), ('clip_completed', 'Clip completed'), ('clip_failed', 'Clip failed'), ('job_retried', 'Job retried')], max_length=32),
        ),
        migrations.AlterField(
            model_name='derivedoutput',
            name='kind',
            field=models.CharField(choices=[('proxy', 'Proxy'), ('dash', 'Manifest'), ('poster', 'Poster'), ('timeline', 'Timeline sheet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='current_status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Preparing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='job_type',
            field=models.CharField(choices=[('process_asset', 'Prepare asset'), ('create_clip', 'Create clip')], max_length=32),
        ),
    ]
